### ISSUE TITLE
Trying to Calculate Bandgap Power

### ISSUE THREAD

**Issue by sherylcorina** [CharuGupta-eng/OS-power-analysis-tool#3]
Hey Charu,

This is the error that I got after entering my netlist name:

Please enter file name with .cir or .txt (e.g. DFF_TG.cir): inverter.cir
Traceback (most recent call last):
  File "POW.py", line 6, in <module>
    s= input("Please enter file name with .cir or .txt (e.g. DFF_TG.cir): ")
  File "<string>", line 1, in <module>
NameError: name 'inverter' is not defined

Please look into it.
P.S.: I'm using Python 2.7.17

**Comment by sherylcorina** [comment]
Hi Charu,
Tried your tool to calculate leakage power using Python3 and it worked well. Thanks.
